-- lib/commands.lua
-- Copyright (c) 2026 Pancakse
-- SPDX-License-Identifier: BSD-3-Clause
-- Descriptions for all built-in AetherOS commands, shared by `help` and `man`.

return {
    { name = "ls", usage = "ls [path]", desc = "List directory contents." },
    { name = "cd", usage = "cd [path]", desc = "Change the current directory." },
    { name = "pwd", usage = "pwd", desc = "Print the current working directory." },
    { name = "cat", usage = "cat <file>", desc = "Print the contents of a file." },
    { name = "echo", usage = "echo <text>", desc = "Print text to the screen." },
    { name = "mkdir", usage = "mkdir <dir>", desc = "Create a new directory." },
    { name = "rm", usage = "rm <path>", desc = "Delete a file or directory." },
    { name = "cp", usage = "cp <src> <dst>", desc = "Copy a file or directory." },
    { name = "mv", usage = "mv <src> <dst>", desc = "Move or rename a file or directory." },
    { name = "touch", usage = "touch <file>", desc = "Create an empty file." },
    { name = "clear", usage = "clear", desc = "Clear the terminal screen." },
    { name = "edit", usage = "edit <file>", desc = "Open the AetherOS text editor." },
    { name = "ps", usage = "ps", desc = "List running AetherOS processes." },
    { name = "kill", usage = "kill <pid>", desc = "Terminate a process by PID." },
    { name = "df", usage = "df", desc = "Show disk space usage." },
    { name = "date", usage = "date", desc = "Show the current in-game date and time." },
    { name = "whoami", usage = "whoami", desc = "Print the current username." },
    { name = "neofetch", usage = "neofetch", desc = "Show a system information summary." },
    { name = "uname", usage = "uname", desc = "Print AetherOS system information." },
    { name = "history", usage = "history", desc = "Show recent shell command history." },
    { name = "peripherals", usage = "peripherals", desc = "List all attached peripherals." },
    { name = "createctl", usage = "createctl <cmd>", desc = "Command-line control for Create machinery (CC:C Bridge)." },
    { name = "createui", usage = "createui", desc = "Open the graphical Create Control app." },
    { name = "gui", usage = "gui", desc = "Launch the AetherOS desktop environment." },
    { name = "files", usage = "files", desc = "Open the Files app." },
    { name = "settings", usage = "settings", desc = "Open the Settings app." },
    { name = "taskmgr", usage = "taskmgr", desc = "Open the Task Manager app." },
    { name = "recovery", usage = "recovery", desc = "Launch the recovery shell (repair/diagnose/reset)." },
    { name = "sudo", usage = "sudo <command>", desc = "Run a command, checking /sbin first." },
    { name = "su", usage = "su <name>", desc = "Switch the active user." },
    { name = "users", usage = "users", desc = "List AetherOS users." },
    { name = "passwd", usage = "passwd [root] [clear]", desc = "Set/clear your login password, or (with 'root') the sudo password." },
    { name = "mkuser", usage = "mkuser <name>", desc = "(sbin) Create a new user." },
    { name = "rmuser", usage = "rmuser <name>", desc = "(sbin) Delete a user." },
    { name = "update", usage = "update [check|install]", desc = "Check for or install AetherOS updates." },
    { name = "reboot", usage = "reboot [recovery]", desc = "Restart the computer, optionally into recovery mode." },
    { name = "shutdown", usage = "shutdown", desc = "Power off the computer." },
    { name = "help", usage = "help [command]", desc = "List commands, or show detail for one command." },
    { name = "man", usage = "man <command>", desc = "Show detailed help for a command." },
    { name = "exit", usage = "exit", desc = "Exit the current shell." },
}
